import type { ResumeSeoCluster } from "./types";

export const yourAiResumeClusters: ResumeSeoCluster[] = [
  {
    id: "your-ai-resume",
    name: "Your AI-Resume",
    verdict: "build",
    primaryKeyword: "your AI resume",
    supportingKeywords: ["AI resume", "AI-resume", "AI resume proof", "proof-backed resume", "verified AI resume"],
    searchIntent: "The searcher wants a resume that reflects AI capability, but may not yet know how to prove the claims.",
    likelyAudience: ["AI-capable job seekers", "Career switchers", "Recruiters"],
    commercialValue: "high",
    recommendedPageType: "Product category page",
    titleTag: "Your AI-Resume: A Resume Backed by Proof of AI Work",
    metaDescription: "Build an AI-resume that links claims to verified AI work samples, receipts, and proof artifacts.",
    internalLinks: ["/ai-work-portfolio", "/ai-capability-proof", "/resumes-vs-proof-of-work"],
    cta: "Build your proof-backed AI-resume",
  },
  {
    id: "ai-generated-resumes",
    name: "AI-generated resumes",
    verdict: "build",
    primaryKeyword: "AI-generated resumes",
    supportingKeywords: ["AI resume problem", "AI resumes hiring", "AI written resume", "AI resume authenticity", "AI resume red flags"],
    searchIntent: "The searcher is worried that AI-written resumes are becoming generic, inflated, or hard to trust.",
    likelyAudience: ["Recruiters", "Hiring managers", "Candidates"],
    commercialValue: "very-high",
    recommendedPageType: "Problem-aware comparison page",
    titleTag: "AI-Generated Resumes Are Not Enough: Show Proof Behind the Claims",
    metaDescription: "AI can polish a resume. ProofOfAIWork shows the real AI-assisted work behind the claims.",
    internalLinks: ["/resumes-vs-proof-of-work", "/ai-work-samples", "/hire-ai-capable-talent"],
    cta: "Replace resume claims with proof artifacts",
  },
  {
    id: "ai-resume-vs-proof-of-work",
    name: "AI resume vs proof of work",
    verdict: "build",
    primaryKeyword: "AI resume vs proof of work",
    supportingKeywords: ["resume vs proof of work", "AI resume proof", "proof-backed resume", "resume proof artifacts"],
    searchIntent: "The searcher is comparing claim-based career documents with evidence-based hiring artifacts.",
    likelyAudience: ["Hiring teams", "Recruiters", "Candidates"],
    commercialValue: "very-high",
    recommendedPageType: "Comparison page",
    titleTag: "AI Resume vs Proof of Work: What Employers Can Actually Trust",
    metaDescription: "Compare AI-polished resumes with proof-backed work samples that show real capability.",
    internalLinks: ["/resumes-vs-proof-of-work", "/ai-capability-proof", "/ai-work-samples"],
    cta: "See proof-backed work samples",
  },
  {
    id: "verified-ai-resume",
    name: "Verified AI resume",
    verdict: "build",
    primaryKeyword: "verified AI resume",
    supportingKeywords: ["verified resume", "AI resume verification", "resume with work samples", "resume with proof links"],
    searchIntent: "The searcher wants a resume or profile that can substantiate skill claims.",
    likelyAudience: ["Candidates", "Freelancers", "Recruiters"],
    commercialValue: "high",
    recommendedPageType: "Feature and template page",
    titleTag: "Verified AI Resume: Link Every AI Skill Claim to Real Work",
    metaDescription: "Create a verified AI resume with linked proof artifacts, work samples, and receipts.",
    internalLinks: ["/ai-work-portfolio", "/verified-ai-work-samples", "/linkedin-profiles-vs-proof-artifacts"],
    cta: "Create a verified AI resume",
  },
  {
    id: "ai-resume-builder",
    name: "AI resume builder",
    verdict: "supporting",
    primaryKeyword: "AI resume builder",
    supportingKeywords: ["free AI resume builder", "ATS AI resume builder", "AI resume maker", "AI resume generator"],
    searchIntent: "The searcher wants software to generate or tailor a traditional resume.",
    likelyAudience: ["Job seekers"],
    commercialValue: "medium",
    recommendedPageType: "Supporting alternative page only",
    titleTag: "AI Resume Builder Alternative: Build Proof, Not Just Resume Text",
    metaDescription: "Most AI resume builders polish claims. ProofOfAIWork helps you show the work behind them.",
    internalLinks: ["/your-ai-resume", "/ai-work-portfolio", "/portfolios-vs-verified-work-samples"],
    cta: "Build a proof-backed AI-resume",
  },
];
