import type { ResumeSeoPage } from "./types";

export const yourAiResumePages: ResumeSeoPage[] = [
  {
    priority: 1,
    slug: "your-ai-resume",
    title: "Your AI-Resume",
    seoTitle: "Your AI-Resume: A Resume Backed by Proof of AI Work",
    metaDescription: "Build an AI-resume that links claims to verified AI work samples, receipts, and proof artifacts.",
    pageType: "Product category page",
    intent: "Capture people looking for an AI resume and convert them to proof-backed career evidence.",
    audience: ["AI-capable job seekers", "Career switchers", "Freelancers"],
    commercialValue: "high",
    angle: "The resume is the index. The proof artifacts are the evidence.",
    sections: ["What an AI-resume should prove", "Why AI-written resumes are weak signal", "What a proof-backed resume includes", "Example AI-resume layout", "How employers inspect it", "Create yours"],
    proofAssets: ["Linked work receipt", "AI capability badge", "Work sample gallery", "Claim-to-proof map"],
    internalLinks: ["/ai-work-portfolio", "/ai-capability-proof", "/resumes-vs-proof-of-work"],
    cta: "Build your proof-backed AI-resume",
  },
  {
    priority: 2,
    slug: "ai-generated-resumes-are-not-enough",
    title: "AI-Generated Resumes Are Not Enough",
    seoTitle: "AI-Generated Resumes Are Not Enough: Show Proof Behind the Claims",
    metaDescription: "AI can polish a resume. ProofOfAIWork shows the real AI-assisted work behind the claims.",
    pageType: "Problem-aware editorial page",
    intent: "Reach recruiters and candidates worried about AI-polished sameness and declining resume trust.",
    audience: ["Recruiters", "Hiring managers", "Candidates"],
    commercialValue: "very-high",
    angle: "AI makes resumes cheaper to produce, so proof becomes more valuable.",
    sections: ["The AI resume flood", "Why polished claims are not proof", "What employers need to inspect", "How candidates can stand out honestly", "Proof-backed resume workflow"],
    proofAssets: ["Resume claim versus proof artifact", "Hiring screen checklist", "Candidate proof workflow"],
    internalLinks: ["/resumes-vs-proof-of-work", "/ai-work-samples", "/hire-ai-capable-talent"],
    cta: "Replace resume claims with proof artifacts",
  },
  {
    priority: 3,
    slug: "ai-resume-vs-proof-of-work",
    title: "AI Resume vs Proof of Work",
    seoTitle: "AI Resume vs Proof of Work: What Employers Can Actually Trust",
    metaDescription: "Compare AI-polished resumes with proof-backed work samples that show real capability.",
    pageType: "Comparison page",
    intent: "Intercept comparison searches and move them toward ProofOfAIWork's evidence model.",
    audience: ["Hiring teams", "Recruiters", "Candidates"],
    commercialValue: "very-high",
    angle: "A resume summarizes claims; proof of work lets people inspect the claim.",
    sections: ["What an AI resume does well", "Where it fails", "What proof of work adds", "Side-by-side comparison", "Recommended hiring workflow"],
    proofAssets: ["Comparison table", "Proof artifact anatomy", "Review rubric"],
    internalLinks: ["/resumes-vs-proof-of-work", "/ai-skills-tests-vs-work-samples", "/ai-work-samples"],
    cta: "See proof-backed work samples",
  },
  {
    priority: 4,
    slug: "verified-ai-resume",
    title: "Verified AI Resume",
    seoTitle: "Verified AI Resume: Link Every AI Skill Claim to Real Work",
    metaDescription: "Create a verified AI resume with linked proof artifacts, work samples, and receipts.",
    pageType: "Feature and template page",
    intent: "Capture candidates who want a more credible resume/profile format.",
    audience: ["Candidates", "Freelancers", "Students"],
    commercialValue: "high",
    angle: "Verification means claims link to inspectable evidence, not that a resume is magically certified.",
    sections: ["What verified should mean", "Claim-to-proof mapping", "Work sample links", "Receipt links", "Profile sharing", "Template"],
    proofAssets: ["Claim-to-proof map", "Verified sample links", "Resume section template"],
    internalLinks: ["/ai-work-portfolio", "/verified-ai-work-samples", "/linkedin-profiles-vs-proof-artifacts"],
    cta: "Create a verified AI resume",
  },
  {
    priority: 5,
    slug: "ai-resume-builder-alternative",
    title: "AI Resume Builder Alternative",
    seoTitle: "AI Resume Builder Alternative: Build Proof, Not Just Resume Text",
    metaDescription: "Most AI resume builders polish claims. ProofOfAIWork helps you show the work behind them.",
    pageType: "Alternative page",
    intent: "Serve AI resume builder searches without competing on templates or ATS scoring.",
    audience: ["Job seekers", "Career coaches", "Recruiters"],
    commercialValue: "medium-high",
    angle: "Use AI to organize proof, not just produce better-sounding bullets.",
    sections: ["What AI resume builders do", "The signal problem", "Proof-backed alternative", "When to use both", "How to start"],
    proofAssets: ["Builder versus proof comparison", "Proof-backed resume template", "Artifact checklist"],
    internalLinks: ["/your-ai-resume", "/ai-work-portfolio", "/ai-capability-proof"],
    cta: "Build a proof-backed AI-resume",
  },
  {
    priority: 6,
    slug: "ai-resume-for-ai-capable-candidates",
    title: "AI Resume for AI-Capable Candidates",
    seoTitle: "AI Resume for AI-Capable Candidates",
    metaDescription: "Show employers how you actually use AI with linked work samples and proof artifacts.",
    pageType: "Candidate page",
    intent: "Help candidates translate AI capability into career evidence.",
    audience: ["Candidates", "Students", "Career switchers"],
    commercialValue: "medium-high",
    angle: "Do not claim AI capability. Show the work pattern behind it.",
    sections: ["What employers need to see", "AI skills worth proving", "Sample proof-backed resume sections", "Portfolio links", "Application workflow"],
    proofAssets: ["Candidate resume template", "AI skills proof checklist", "Sample proof links"],
    internalLinks: ["/ai-work-portfolio", "/prompt-engineering-proof", "/student-ai-portfolio"],
    cta: "Build your AI work portfolio",
  },
  {
    priority: 7,
    slug: "ai-resume-for-hiring-teams",
    title: "AI Resume for Hiring Teams",
    seoTitle: "AI Resumes for Hiring Teams: How to Evaluate Proof Behind Claims",
    metaDescription: "Learn how hiring teams can evaluate AI-polished resumes by asking for proof artifacts.",
    pageType: "Employer page",
    intent: "Help employers adapt screening to AI-polished applications.",
    audience: ["Hiring managers", "Recruiters", "Founders"],
    commercialValue: "very-high",
    angle: "The answer to AI-polished applications is not more suspicion. It is better evidence.",
    sections: ["What changed in screening", "AI resume red flags", "Proof requests that are fair", "Work-sample review workflow", "Scorecard"],
    proofAssets: ["Hiring scorecard", "Proof request template", "Review rubric"],
    internalLinks: ["/hire-ai-capable-talent", "/ai-hiring-scorecard", "/ai-work-samples"],
    cta: "Review candidates with proof",
  },
  {
    priority: 8,
    slug: "ai-resume-proof-examples",
    title: "AI Resume Proof Examples",
    seoTitle: "AI Resume Proof Examples: Claims Linked to Real AI Work",
    metaDescription: "See examples of AI resume claims backed by work samples, receipts, and proof artifacts.",
    pageType: "Examples page",
    intent: "Give concrete examples that make the concept inspectable.",
    audience: ["Candidates", "Recruiters", "Career coaches"],
    commercialValue: "high",
    angle: "Every important AI skill claim should have a proof link.",
    sections: ["Example claim-to-proof map", "Marketing example", "Engineering example", "Operations example", "Prompt workflow example", "Build your own"],
    proofAssets: ["Four claim-to-proof examples", "Work receipt previews", "Role-specific links"],
    internalLinks: ["/examples", "/marketing-ai-work-samples", "/engineering-ai-work-samples"],
    cta: "Browse AI resume proof examples",
  },
  {
    priority: 9,
    slug: "how-to-add-proof-to-an-ai-resume",
    title: "How to Add Proof to an AI Resume",
    seoTitle: "How to Add Proof to an AI Resume",
    metaDescription: "Turn AI resume claims into proof links using work samples, receipts, and capability artifacts.",
    pageType: "How-to guide",
    intent: "Give candidates a practical workflow they can complete immediately.",
    audience: ["Candidates", "Freelancers", "Students"],
    commercialValue: "medium-high",
    angle: "Add proof links where claims would otherwise be generic.",
    sections: ["Choose claims worth proving", "Select work samples", "Create receipts", "Add links to resume/profile", "Send with applications"],
    proofAssets: ["Step-by-step checklist", "Resume link template", "Proof artifact examples"],
    internalLinks: ["/ai-work-receipt", "/ai-assisted-workflow", "/ai-work-portfolio"],
    cta: "Add proof to your AI-resume",
  },
  {
    priority: 10,
    slug: "ai-resume-pages-to-avoid",
    title: "AI Resume Pages to Avoid",
    seoTitle: "AI Resume SEO Pages to Avoid",
    metaDescription: "Avoid low-value AI resume SEO pages that attract the wrong traffic or weaken ProofOfAIWork positioning.",
    pageType: "Editorial governance page",
    intent: "Prevent content drift into generic resume-builder SEO.",
    audience: ["Internal marketing", "Editors", "SEO operators"],
    commercialValue: "medium",
    angle: "Traffic without proof intent is a distraction.",
    sections: ["Avoid generic builder pages", "Avoid ATS myths", "Avoid job-title doorway pages", "Avoid fake rankings", "Publish only proof-led pages"],
    proofAssets: ["Avoid list", "Publishing criteria", "Proof relevance checklist"],
    internalLinks: ["/ai-capability-proof", "/ai-work-samples", "/your-ai-resume"],
    cta: "Use the proof-led publishing criteria",
  },
];
