import type { SeoCluster } from "./types";

export const seoKeywordClusters: SeoCluster[] = [
  {
    id: "ai-work-samples",
    name: "AI work samples",
    primaryKeyword: "AI work samples",
    supportingKeywords: ["AI work sample examples", "AI-assisted work samples", "examples of AI work", "AI project samples for hiring", "verified AI work samples"],
    searchIntent: "Find examples of AI-enabled output and understand whether they prove real capability.",
    likelyAudience: ["Hiring managers", "Recruiters", "Candidates", "Freelancers"],
    commercialValue: "high",
    recommendedPageType: "Product-led guide with example gallery",
    sampleTitleTag: "AI Work Samples: How to Prove Real AI Capability",
    sampleMetaDescription: "See what strong AI work samples look like and how employers can evaluate real AI-assisted output.",
    internalLinksNeeded: ["/explore", "/proof-of-ai-work", "/ai-work-portfolio", "/hire-ai-capable-talent"],
    conversionCta: "View verified AI work samples",
  },
  {
    id: "ai-skills-assessment",
    name: "AI skills assessment",
    primaryKeyword: "AI skills assessment",
    supportingKeywords: ["AI skills test", "assess AI skills", "AI competency assessment", "AI hiring assessment", "AI assessment for employees"],
    searchIntent: "Compare ways to evaluate AI capability for hiring, training, or workforce planning.",
    likelyAudience: ["Talent leaders", "Recruiters", "Hiring managers", "Learning and development teams"],
    commercialValue: "very-high",
    recommendedPageType: "Comparison page and assessment framework",
    sampleTitleTag: "AI Skills Assessment: Tests vs Real Work Samples",
    sampleMetaDescription: "Learn why AI skills tests miss workflow judgment, tool use, and real execution evidence.",
    internalLinksNeeded: ["/ai-skills-tests-vs-work-samples", "/ai-capability-proof", "/workforce-ai-readiness"],
    conversionCta: "Assess AI capability with work evidence",
  },
  {
    id: "ai-leverage",
    name: "AI leverage",
    primaryKeyword: "AI leverage",
    supportingKeywords: ["AI leverage score", "measure AI productivity", "AI productivity proof", "AI leverage at work", "workforce amplification"],
    searchIntent: "Describe and measure how much better someone works with AI.",
    likelyAudience: ["Founders", "Operators", "Team leads", "Workforce strategists"],
    commercialValue: "high",
    recommendedPageType: "Category explainer with scoring rubric",
    sampleTitleTag: "AI Leverage: Measuring Who Gets More Done With AI",
    sampleMetaDescription: "AI leverage is the ability to turn AI tools into better, faster work. Here is how to prove it.",
    internalLinksNeeded: ["/ai-capability-scorecard", "/ai-assisted-workflow", "/workforce-ai-readiness"],
    conversionCta: "Measure AI leverage",
  },
  {
    id: "ai-capability-proof",
    name: "AI capability proof",
    primaryKeyword: "AI capability proof",
    supportingKeywords: ["proof of AI capability", "prove AI skills", "demonstrated AI capability", "AI skill evidence", "proof of AI work"],
    searchIntent: "Find credible evidence that a person can actually use AI in real work.",
    likelyAudience: ["Hiring teams", "Founders", "Candidates", "Enterprise buyers"],
    commercialValue: "very-high",
    recommendedPageType: "Core category hub",
    sampleTitleTag: "AI Capability Proof: Evidence That Someone Can Actually Use AI",
    sampleMetaDescription: "Replace AI fluency claims with proof artifacts, workflows, receipts, and verified outcomes.",
    internalLinksNeeded: ["/ai-work-samples", "/ai-work-receipt", "/verified-ai-work-samples", "/examples"],
    conversionCta: "Create proof of AI capability",
  },
  {
    id: "hiring-ai-capable-talent",
    name: "Hiring AI-capable talent",
    primaryKeyword: "hiring AI-capable talent",
    supportingKeywords: ["hire AI talent", "hire AI fluent employees", "AI-capable candidates", "AI-native hiring", "candidate AI skills"],
    searchIntent: "Find a better hiring process for people who can use AI to produce stronger work.",
    likelyAudience: ["Founders", "Hiring managers", "Recruiters", "People teams"],
    commercialValue: "very-high",
    recommendedPageType: "Hiring solution page",
    sampleTitleTag: "Hiring AI-Capable Talent: What to Look For Beyond Resumes",
    sampleMetaDescription: "Learn how to identify candidates who can actually amplify their work with AI.",
    internalLinksNeeded: ["/resumes-vs-proof-of-work", "/ai-hiring-scorecard", "/ai-work-samples"],
    conversionCta: "Review AI-capable candidates",
  },
  {
    id: "workforce-ai-readiness",
    name: "Workforce AI readiness",
    primaryKeyword: "workforce AI readiness",
    supportingKeywords: ["AI readiness assessment", "employee AI readiness", "AI workforce assessment", "team AI skills matrix", "AI adoption readiness"],
    searchIntent: "Understand whether a team can adopt AI productively and where capability gaps are.",
    likelyAudience: ["CHROs", "Learning and development leaders", "Department heads", "Operations executives"],
    commercialValue: "high",
    recommendedPageType: "Assessment playbook",
    sampleTitleTag: "Workforce AI Readiness: Measure Capability, Not Confidence",
    sampleMetaDescription: "Map who can use AI effectively by reviewing real work, not survey self-ratings.",
    internalLinksNeeded: ["/ai-leverage", "/employee-ai-capability-assessment", "/team-ai-readiness-assessment"],
    conversionCta: "Run an AI readiness review",
  },
  {
    id: "prompt-engineering-proof",
    name: "Prompt engineering proof",
    primaryKeyword: "prompt engineering proof",
    supportingKeywords: ["prompt engineering portfolio", "prove prompt engineering skills", "prompt examples for portfolio", "prompt engineering work samples", "AI prompt proof"],
    searchIntent: "Show prompt skill credibly to employers or clients.",
    likelyAudience: ["Candidates", "Freelancers", "Recruiters", "AI trainers"],
    commercialValue: "medium-high",
    recommendedPageType: "Artifact guide",
    sampleTitleTag: "Prompt Engineering Proof: How to Show Real Prompting Skill",
    sampleMetaDescription: "Strong prompt work is visible in task framing, iteration, validation, and final output quality.",
    internalLinksNeeded: ["/ai-work-portfolio", "/ai-assisted-workflow", "/prompt-engineering-portfolio-examples"],
    conversionCta: "Publish a prompt proof artifact",
  },
  {
    id: "ai-assisted-workflow",
    name: "AI-assisted workflow",
    primaryKeyword: "AI-assisted workflow",
    supportingKeywords: ["document AI workflow", "AI workflow example", "AI-assisted work process", "human AI workflow", "AI workflow proof"],
    searchIntent: "Document or inspect the process behind an AI-assisted result.",
    likelyAudience: ["Operators", "Candidates", "Managers", "Consultants"],
    commercialValue: "high",
    recommendedPageType: "Workflow template and how-it-works page",
    sampleTitleTag: "AI-Assisted Workflow: How to Document Human + AI Work",
    sampleMetaDescription: "Show the workflow behind the result: prompts, tool choices, decisions, edits, and impact.",
    internalLinksNeeded: ["/ai-work-receipt", "/proof-of-ai-work", "/examples"],
    conversionCta: "Document an AI-assisted workflow",
  },
  {
    id: "ai-work-portfolio",
    name: "AI portfolio / AI work portfolio",
    primaryKeyword: "AI work portfolio",
    supportingKeywords: ["AI portfolio", "AI work portfolio examples", "AI project portfolio", "AI portfolio for job seekers", "verified AI portfolio"],
    searchIntent: "Build a career asset that proves AI capability through real work.",
    likelyAudience: ["Candidates", "Students", "Freelancers", "Career switchers"],
    commercialValue: "medium-high",
    recommendedPageType: "Candidate acquisition page",
    sampleTitleTag: "AI Work Portfolio: Build a Portfolio That Proves AI Capability",
    sampleMetaDescription: "Create a portfolio of verified AI-assisted work samples employers can inspect.",
    internalLinksNeeded: ["/student-ai-portfolio", "/freelancer-ai-portfolio", "/verified-ai-work-samples"],
    conversionCta: "Build your AI work portfolio",
  },
];

export function getSeoCluster(id: string) {
  return seoKeywordClusters.find((cluster) => cluster.id === id);
}
